version: "3"
services:
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    environment:
      SONAR_JDBC_URL:jdbc:postgresql://clvua2agj001oo7a8k5iw03v3:5432/clvua2agh000la8o712e45pv9
      SONAR_JDBC_USERNAME:clvua2agg000ja8o7eq9th4bo 
      SONAR_JDBC_PASSWORD:pC5a9bSEDj0hPIEdcLOi4eHV
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
