version: "3"
services:
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    environment:
      SONAR_JDBC_URL:${SONAR_JDBC_URL}
      SONAR_JDBC_USERNAME:${SONAR_JDBC_USERNAME}
      SONAR_JDBC_PASSWORD:${SONAR_JDBC_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9001:9001"

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
